version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: slooze-postgres
    restart: always
    environment:
      POSTGRES_USER: slooze
      POSTGRES_PASSWORD: sloozepassword
      POSTGRES_DB: sloozedb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - slooze-network

  backend:
    build:
      context: ./apps/backend
    container_name: slooze-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://slooze:sloozepassword@postgres:5432/sloozedb?schema=public
      - JWT_SECRET=super_secret_jwt_key_for_slooze
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - slooze-network

  frontend:
    build:
      context: ./apps/frontend
    container_name: slooze-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - slooze-network

volumes:
  postgres_data:

networks:
  slooze-network:
    driver: bridge
